name: crosscheck
description: >
  Automated Dependency Management for Dart.
version: 0.1.0
authors:
  - Dart Team <misc@dartlang.org>
homepage: https://github.com/matanlurey/crosscheck

environment:
  sdk: '>=1.24.0 <2.0.0-dev.infinity'

dependencies:
  args: '>=0.13.6+1 <2.0.0'
  yaml: '^2.0.0'
  pub_semver: "^1.3.0"
  path:

dev_dependencies:
  test:

executables:
  crosscheck:
